name: Audit live site
on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Audit live URL
        uses: jakejarvis/lighthouse-action@v0.3.2
        with:
          url: 'https://cheatsheets.xyz'
      - name: Upload results as an artifact
        uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'
